language: php

php:
  - 5.6
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

scrpit:
  - phpunit --verbose

# KOMMENTIT VOI POISTAA KUNHAN ON OIKEA API-KEY HEROKUUN!!!!
#deploy:
#  provider: heroku
#  api_key:
#    secure: kumi-kumi lis채채 t채h채n herokun api-key
#  app: shielded-earth-2316
#  on:
#    repo: OhtuSamurai/drunken-octo-hipster
