language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --verbose
  - phpunit --coverage-clover build/logs/clover.xml
  
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

deploy:
  provider: heroku
  api_key:
    secure: IYkhIPMH/d8+AmQrgdltfTh+u08+/Faki/xq8wlsUBRexN6Z+IEaEiPX/mEzwRl7zY5NXaTHPZT9upHj+9ApEtEB4szp1iKouZ8PhPwX7nb8u9T7vOQulNMdhx79KibUKgai2xMkdraI14mfBBocwzkhGFw1IFKgkT5Crucmmb0=
  app: shielded-earth-2316
  on:
    repo: OhtuSamurai/drunken-octo-hipster
