language: php

php:
  - 5.6
  - 5.5
  - hhvm

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "sudo rackup"
  - sleep 3
  - "wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar"
  - "java -jar selenium-server-standalone-2.44.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &"
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - phpunit --verbose

deploy:
  provider: heroku
  api_key:
    secure: IYkhIPMH/d8+AmQrgdltfTh+u08+/Faki/xq8wlsUBRexN6Z+IEaEiPX/mEzwRl7zY5NXaTHPZT9upHj+9ApEtEB4szp1iKouZ8PhPwX7nb8u9T7vOQulNMdhx79KibUKgai2xMkdraI14mfBBocwzkhGFw1IFKgkT5Crucmmb0=
  app: shielded-earth-2316
  on:
    repo: OhtuSamurai/drunken-octo-hipster

