language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  # Php-coveralls
  #- composer require satooshi/php-coveralls:~0.6@stable

  # Selenium
  #  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar

before_script:
  - psql -c 'create database forge;' -U postgres
  - psql -c 'create user forge WITH PASSWORD \'\';' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE \"forge\" to forge;' -U postgres

  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  - composer self-update
  - composer install --dev --prefer-source --no-interaction

  # for Php-coveralls
  - mkdir -p build/logs

# Selenium: toimii, mutta testaus remotessa ei ole huomioitu
#  - sh -e /etc/init.d/xvfb start
#  - export DISPLAY=:99
#  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 & > /dev/null
#  - sleep 5 

script:
#  - phpunit --verbose --coverage-clover build/logs/clover.xml
  - phantomjs --webdriver=4444 & vendor/bin/codecept run acceptance
  - sudo cat /var/log/apache2/error.log
  - sudo cat /etc/apache2/sites-available/default
  - php --version
  - sudo cat /usr/local/apache2/conf/httpd.conf
  - sudo ls -l /usr/local/bin | grep php

after_success:
  - php vendor/bin/coveralls -v --exclude-no-stmt

deploy:
  provider: heroku
  api_key:
    secure: IYkhIPMH/d8+AmQrgdltfTh+u08+/Faki/xq8wlsUBRexN6Z+IEaEiPX/mEzwRl7zY5NXaTHPZT9upHj+9ApEtEB4szp1iKouZ8PhPwX7nb8u9T7vOQulNMdhx79KibUKgai2xMkdraI14mfBBocwzkhGFw1IFKgkT5Crucmmb0=
  app: shielded-earth-2316
  on:
    repo: OhtuSamurai/drunken-octo-hipster
