language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  # Php-coveralls
  - composer require satooshi/php-coveralls:~0.6@stable
  
  # Selenium
  #  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar

before_script:
  # Install Apache
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl > /dev/null
  - sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

  - composer self-update
  - composer install --dev --prefer-source --no-interaction

  # for Php-coveralls
  - mkdir -p build/logs

# Selenium: toimii, mutta testaus remotessa ei ole huomioitu
#  - sh -e /etc/init.d/xvfb start
#  - export DISPLAY=:99
#  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 & > /dev/null
#  - sleep 5 

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml
  - phantomjs --webdriver=4444 & vendor/bin/codecept run acceptance


after_success:
  - php vendor/bin/coveralls -v --exclude-no-stmt

deploy:
  provider: heroku
  api_key:
    secure: IYkhIPMH/d8+AmQrgdltfTh+u08+/Faki/xq8wlsUBRexN6Z+IEaEiPX/mEzwRl7zY5NXaTHPZT9upHj+9ApEtEB4szp1iKouZ8PhPwX7nb8u9T7vOQulNMdhx79KibUKgai2xMkdraI14mfBBocwzkhGFw1IFKgkT5Crucmmb0=
  app: shielded-earth-2316
  on:
    repo: OhtuSamurai/drunken-octo-hipster
