<?php 
$I = new FunctionalTester($scenario);
$I->wantTo('Create a user as admin');
$I->loginAsAdmin();
$I->amOnPage('/');
$I->click('Poolin ulkopuoliset käyttäjät');
$I->click('Luo uusi käyttäjä');
$I->seeInCurrentUrl('user/create');
$I->fillField('username', 'pelle');
$I->click('Luo käyttäjä');
$I->seeInCurrentUrl('user/create');
$I->see('Anna etunimi.');
$I->dontSee('Anna käyttäjätunnus.');
$I->seeInField('username', 'pelle');
$I->fillField('first_name', 'Pelle');
$I->fillField('last_name', 'Peloton');
$I->fillField('email', 'Pelle@ankkalinna');
$I->fillField('department', 'innovations');
$I->fillField('position', 'inventor');
$I->fillField('description', 'abc');
$I->click('Luo käyttäjä');
$I->seeInCurrentUrl('user/create');
$I->see('Sähköpostiosoitteen täytyy olla kelvollinen.');
$I->fillField('email', 'pelle@example.com');
$I->click('Luo käyttäjä');
$I->see('Käyttäjä pelle on luotu järjestelmään.');
$I->seeInCurrentUrl('poistetut');
$I->see('Pelle');
$I->see('Peloton');
$I->see('pelle@example.com');
$I->see('innovations');
$I->see('inventor');
$I->click('Pelle');
$I->see('abc');